### ISSUE TITLE
Disable uncaching in install tool

### ISSUE THREAD

**Issue by vertexvaar** [NamelessCoder/uncache#13]
I know the flowchart is strict about caches beeing active at any point of time, but something i often have to deal with is that compare database always wants to drop the cache tables beacuse there is no database backend configured and i often forget about that.

Would you, just to know before i provide a PR, allow a condition that disables the uncaching for install tool requests or do you want to keep it nice and clean?

**Comment by NamelessCoder** [comment]
Sounds fine to me - the install tool doesn't use caches in the first place :)
